server:
  port: 8080
spring:
  application:
    name: chickenhouse_precificacao
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/chickenhouse?allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: root
    password: leonan2knet